### ISSUE TITLE
**Description**의 변경을 요청합니다!

### ISSUE THREAD

**Issue by jeonghyeon-net** [Las-Wonho/Notifications#6]
이 프로젝트가 발전되었기 때문에, 그에 맞추어 Description의 내용을 변경하여야한다고  생각합니다.

topics 도 업데이트하고, website에 서버 링크를 올려보는 건 어떨까요?

**Comment by MagicalLas** [comment]
그건 선우 브랜치에서 해주세요. 메인 브랜치는 예전 그대로 놔두려고합니다.

**Comment by jeonghyeon-net** [comment]
아 알겠습니당
